// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/google/uuid"
)

type Book struct {
	ID      uuid.UUID
	Name    string
	Author  string
	Genre   string
	UserIds []uuid.UUID
}

type User struct {
	ID       uuid.UUID
	Name     string
	Email    string
	Password string
}
